In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [62]:
df = pd.read_csv("data_poverty/ACSST5Y2018.S1701_data_with_overlays_2020-11-02T143849.csv", header = 0)

In [63]:
df.head()

,GEO_ID,NAME,S1701_C01_001E,S1701_C01_001M,S1701_C02_001E,S1701_C02_001M,S1701_C03_001E,S1701_C03_001M,S1701_C01_002E,S1701_C01_002M,...,S1701_C02_060E,S1701_C02_060M,S1701_C03_060E,S1701_C03_060M,S1701_C01_061E,S1701_C01_061M,S1701_C02_061E,S1701_C02_061M,S1701_C03_061E,S1701_C03_061M
0,id,Geographic Area Name,Estimate!!Total!!Population for whom poverty s...,Margin of Error!!Total MOE!!Population for who...,Estimate!!Below poverty level!!Population for ...,Margin of Error!!Below poverty level MOE!!Popu...,Estimate!!Percent below poverty level!!Populat...,Margin of Error!!Percent below poverty level M...,Estimate!!Total!!Population for whom poverty s...,Margin of Error!!Total MOE!!Population for who...,...,Estimate!!Below poverty level!!UNRELATED INDIV...,Margin of Error!!Below poverty level MOE!!UNRE...,Estimate!!Percent below poverty level!!UNRELAT...,Margin of Error!!Percent below poverty level M...,Estimate!!Total!!UNRELATED INDIVIDUALS FOR WHO...,Margin of Error!!Total MOE!!UNRELATED INDIVIDU...,Estimate!!Below poverty level!!UNRELATED INDIV...,Margin of Error!!Below poverty level MOE!!UNRE...,Estimate!!Percent below poverty level!!UNRELAT...,Margin of Error!!Percent below poverty level M...
1,0400000US42,Pennsylvania,12380149,2042,1578949,16967,12.8,0.1,2628648,2038,...,199737,3499,38.7,0.5,959183,6376,382263,4761,39.9,0.4
2,8600000US19102,ZCTA5 19102,4564,476,653,238,14.3,5.0,137,73,...,333,177,44.9,16.8,427,138,247,127,57.8,20.4
3,8600000US19103,ZCTA5 19103,23802,953,2098,293,8.8,1.2,1431,263,...,764,186,23.9,5.3,3116,390,1083,245,34.8,6.0
4,8600000US19104,ZCTA5 19104,40263,1644,18259,1577,45.3,2.9,7666,821,...,3751,391,58.1,3.6,8699,959,7369,913,84.7,2.8

In [64]:
df['total_population'] = df['S1701_C01_001E']
df['below_poverty'] = df['S1701_C02_001E']
df['percent_below_poverty'] = df['S1701_C03_001E']
df['unrelated_individuals_population'] = df['S1701_C01_046E']
df['unrelated_individuals_below_poverty'] = df['S1701_C02_046E']
df['unrelated_individuals_percent_below_poverty'] = df['S1701_C03_046E']
df['income_below_50percent_poverty_level'] = df['S1701_C01_038E']
df['income_below_125percent_poverty_level'] = df['S1701_C01_039E']
df['income_below_150percent_poverty_level'] = df['S1701_C01_040E']
df['income_below_185percent_poverty_level'] = df['S1701_C01_041E']
df['income_below_200percent_poverty_level'] = df['S1701_C01_042E']
df['income_below_300percent_poverty_level'] = df['S1701_C01_043E']
df['income_below_400percent_poverty_level'] = df['S1701_C01_044E']
df['income_below_500percent_poverty_level'] = df['S1701_C01_045E']
df['mean_income_deficit_unrelated_individuals'] = df['S1701_C01_058E']

In [65]:
# double check the columns
columns = ['total_population', 
           'below_poverty', 
           'percent_below_poverty', 
           'unrelated_individuals_population',
           'unrelated_individuals_below_poverty',
           'unrelated_individuals_percent_below_poverty',
           'income_below_50percent_poverty_level',
           'income_below_125percent_poverty_level',
           'income_below_150percent_poverty_level',
           'income_below_185percent_poverty_level',
           'income_below_200percent_poverty_level',
           'income_below_300percent_poverty_level',
           'income_below_400percent_poverty_level',
           'income_below_500percent_poverty_level',
           'mean_income_deficit_unrelated_individuals']
for col in columns:
    print(col)
    print(df.at[0,col], '\n')

total_population
Estimate!!Total!!Population for whom poverty status is determined

below_poverty
Estimate!!Below poverty level!!Population for whom poverty status is determined

percent_below_poverty
Estimate!!Percent below poverty level!!Population for whom poverty status is determined

unrelated_individuals_population
Estimate!!Total!!UNRELATED INDIVIDUALS FOR WHOM POVERTY STATUS IS DETERMINED

unrelated_individuals_below_poverty
Estimate!!Below poverty level!!UNRELATED INDIVIDUALS FOR WHOM POVERTY STATUS IS DETERMINED

unrelated_individuals_percent_below_poverty
Estimate!!Percent below poverty level!!UNRELATED INDIVIDUALS FOR WHOM POVERTY STATUS IS DETERMINED

income_below_50percent_poverty_level
Estimate!!Total!!Population for whom poverty status is determined!!ALL INDIVIDUALS WITH INCOME BELOW THE FOLLOWING POVERTY RATIOS!!50 percent of poverty level

income_below_125percent_poverty_level
Estimate!!Total!!Population for whom poverty status is determined!!ALL INDIVIDUALS WITH INCOME BELOW THE FOLLOWING POVERTY RATIOS!!125 percent of poverty level

income_below_150percent_poverty_level
Estimate!!Total!!Population for whom poverty status is determined!!ALL INDIVIDUALS WITH INCOME BELOW THE FOLLOWING POVERTY RATIOS!!150 percent of poverty level

income_below_185percent_poverty_level
Estimate!!Total!!Population for whom poverty status is determined!!ALL INDIVIDUALS WITH INCOME BELOW THE FOLLOWING POVERTY RATIOS!!185 percent of poverty level

income_below_200percent_poverty_level
Estimate!!Total!!Population for whom poverty status is determined!!ALL INDIVIDUALS WITH INCOME BELOW THE FOLLOWING POVERTY RATIOS!!200 percent of poverty level

income_below_300percent_poverty_level
Estimate!!Total!!Population for whom poverty status is determined!!ALL INDIVIDUALS WITH INCOME BELOW THE FOLLOWING POVERTY RATIOS!!300 percent of poverty level

income_below_400percent_poverty_level
Estimate!!Total!!Population for whom poverty status is determined!!ALL INDIVIDUALS WITH INCOME BELOW THE FOLLOWING POVERTY RATIOS!!400 percent of poverty level

income_below_500percent_poverty_level
Estimate!!Total!!Population for whom poverty status is determined!!ALL INDIVIDUALS WITH INCOME BELOW THE FOLLOWING POVERTY RATIOS!!500 percent of poverty level

mean_income_deficit_unrelated_individuals
Estimate!!Total!!UNRELATED INDIVIDUALS FOR WHOM POVERTY STATUS IS DETERMINED!!Mean income deficit for unrelated individuals (dollars)

In [66]:
# drop PA state-level information 
df.drop([0,1], inplace = True)

# get cleaned zipcode
df["zipcode"] = df["GEO_ID"].apply(lambda x: x[-5:])
df.rename(columns = {"GEO_ID": "zipcode"})

columns.insert(0, "zipcode")
df = df[columns]

df.reset_index(drop = True, inplace = True)

In [69]:
df.head()

,zipcode,total_population,below_poverty,percent_below_poverty,unrelated_individuals_population,unrelated_individuals_below_poverty,unrelated_individuals_percent_below_poverty,income_below_50percent_poverty_level,income_below_125percent_poverty_level,income_below_150percent_poverty_level,income_below_185percent_poverty_level,income_below_200percent_poverty_level,income_below_300percent_poverty_level,income_below_400percent_poverty_level,income_below_500percent_poverty_level,mean_income_deficit_unrelated_individuals
0,19102,4564,653,14.3,2818,598,21.2,530,724,749,874,890,1167,1577,1889,9071
1,19103,23802,2098,8.8,14078,1949,13.8,1292,3030,3656,4258,4477,6988,8812,11018,7775
2,19104,40263,18259,45.3,19972,11323,56.7,12515,21210,22768,25431,26189,31511,34246,36200,9183
3,19106,11372,851,7.5,5754,825,14.3,615,997,1063,1384,1431,2081,2894,4416,8548
4,19107,12518,2917,23.3,8102,2337,28.8,1641,3630,3970,4327,4504,6062,7124,8308,8457

In [68]:
df.to_csv('data_poverty/cleaned_poverty.csv', index = False)